# Generated by Django 2.0.7 on 2018-07-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('artificial_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Form_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_date', models.DateTimeField(verbose_name='date answered')),
                ('user', models.EmailField(max_length=254)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Form')),
            ],
        ),
    ]
