# Generated by Django 2.0.7 on 2018-07-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0008_auto_20180709_2217'),
        ('discourse_form', '0002_auto_20180709_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sessions_coding.Classroom_session'),
        ),
    ]
