# Generated by Django 2.0.7 on 2018-07-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0009_auto_20180710_1304'),
        ('discourse_form', '0004_auto_20180710_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answered_axis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Form_answer')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_coding.Axis')),
            ],
        ),
        migrations.CreateModel(
            name='Answered_copus_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Form_answer')),
                ('copus_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_coding.Copus_code')),
            ],
        ),
        migrations.CreateModel(
            name='Answered_learning_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Form_answer')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_coding.Learning_goal')),
            ],
        ),
        migrations.CreateModel(
            name='Answered_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Form_answer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_coding.Skill')),
            ],
        ),
        migrations.AlterField(
            model_name='answered_subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions_coding.Subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
