# Generated by Django 2.0.7 on 2018-07-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0009_auto_20180710_1304'),
        ('discourse_form', '0005_auto_20180710_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Discourse_form',
        ),
    ]
