# Generated by Django 2.0.7 on 2018-07-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_form', '0006_auto_20180710_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='discourse_form',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
