# Generated by Django 2.0.7 on 2018-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_form', '0007_discourse_form_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_answer',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
