# Generated by Django 2.0.5 on 2018-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_form', '0010_answered_skill_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_answer',
            name='dialogic',
            field=models.CharField(blank=True, default='NA', max_length=20),
        ),
    ]
