# Generated by Django 2.0.5 on 2018-07-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_form', '0011_form_answer_dialogic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answered_skill_phrases',
            name='code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
