# Generated by Django 2.0.5 on 2018-07-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_form', '0012_answered_skill_phrases_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answered_copus_phrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, default=0)),
                ('phrases', models.TextField()),
                ('ans_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Form_answer')),
                ('copus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Answered_copus_code')),
            ],
        ),
        migrations.CreateModel(
            name='Answered_dialogic_phrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogic', models.CharField(choices=[('autoritativo', 'Autoritativo'), ('dialogico', 'Dialógico')], max_length=20)),
                ('code', models.IntegerField(blank=True, default=0)),
                ('phrases', models.TextField()),
                ('ans_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discourse_form.Form_answer')),
            ],
        ),
    ]
