# Generated by Django 2.0.5 on 2018-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_form', '0013_answered_copus_phrases_answered_dialogic_phrases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answered_dialogic_phrases',
            name='dialogic',
            field=models.CharField(choices=[('Autoritativo', 'Autoritativo'), ('Dialogico', 'Dialógico'), ('NA', 'NA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='form_answer',
            name='dialogic',
            field=models.CharField(blank=True, default='NA', max_length=40),
        ),
    ]
