# Generated by Django 2.0.5 on 2018-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse_form', '0014_auto_20180730_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discourse_form',
            name='artificial_name',
            field=models.CharField(max_length=100),
        ),
    ]
