# Generated by Django 2.0.7 on 2018-07-10 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0003_auto_20180709_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='axis',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sessions_coding.Grade'),
        ),
    ]
