# Generated by Django 2.0.7 on 2018-07-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0004_axis_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning_goal',
            name='goal_name',
            field=models.CharField(max_length=100),
        ),
    ]
