# Generated by Django 2.0.7 on 2018-07-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0006_auto_20180709_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_session',
            name='path',
            field=models.FilePathField(max_length=300, path='C:\\Users\\usuario\\Documents\\Python Scripts\\topic_forms\\teacher_discourse_form\\data\\textos_ulloa'),
        ),
    ]
