# Generated by Django 2.0.7 on 2018-07-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0007_auto_20180709_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_session',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
