# Generated by Django 2.0.7 on 2018-07-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0009_auto_20180710_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis',
            name='axis',
            field=models.CharField(max_length=50),
        ),
    ]
