# Generated by Django 2.0.5 on 2018-07-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0010_auto_20180716_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_session',
            name='path',
            field=models.FilePathField(blank=True, max_length=300, path='C:\\Users\\usuario\\Documents\\Python Scripts\\topic_forms\\teacher_discourse_form\\data\\textos_ulloa'),
        ),
    ]
