# Generated by Django 2.0.5 on 2018-07-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0012_auto_20180719_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
