# Generated by Django 2.0.5 on 2018-07-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0015_auto_20180723_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copus_code',
            options={'ordering': ['pk']},
        ),
    ]
