# Generated by Django 2.0.5 on 2018-07-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0016_auto_20180730_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom_session',
            name='wav_name',
            field=models.CharField(max_length=100),
        ),
    ]
