# Generated by Django 2.0.5 on 2018-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_coding', '0018_auto_20180730_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom_session',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
